### ISSUE TITLE
install/compilation failure

### ISSUE THREAD

**Issue by mehar** [fede1024/kafka-benchmark#7]
Compiling kafka-benchmark v0.2.0 (/Users/mesimhad/research/kafka-benchmark)
error[E0599]: no method named `send_copy` found for type `rdkafka::producer::BaseProducer<producer::BenchmarkProducerContext>` in the current scope
  --> src/producer/mod.rs:55:10
   |
55 |         .send_copy::<str, str>(&scenario.topic, None, Some("warmup"), None, (), None)
   |          ^^^^^^^^^

error[E0599]: no method named `send_copy` found for type `rdkafka::producer::BaseProducer<producer::BenchmarkProducerContext>` in the current scope
  --> src/producer/mod.rs:68:28
   |
68 |             match producer.send_copy::<[u8], [u8]>(
   |                            ^^^^^^^^^

error[E0599]: no method named `send_copy` found for type `rdkafka::producer::FutureProducer` in the current scope
   --> src/producer/mod.rs:119:10
    |
119 |         .send_copy::<str, str>(&scenario.topic, None, Some("warmup"), None, None, 1000)
    |          ^^^^^^^^^

error[E0599]: no method named `send_copy` found for type `rdkafka::producer::FutureProducer` in the current scope
   --> src/producer/mod.rs:131:31
    |
131 |         futures.push(producer.send_copy::<[u8], [u8]>(
    |                               ^^^^^^^^^

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0599`.
error: failed to compile `kafka-benchmark v0.2.0 (/Users/mesimhad/research/kafka-benchmark)`, intermediate artifacts can be found at `/Users/mesimhad/research/kafka-benchmark/target`

Caused by:
  Could not compile `kafka-benchmark`.

To learn more, run the command again with --verbose.

**Comment by icunhacorrea** [comment]
I had the same issue, anyone have the solution for this? Thanks.

**Comment by renier** [comment]
Builds with rust 1.23.0
